    //! Tests de la mesure de couverture de détection (purple-team, blue-team value) : migration MITRE
    //! idempotente, propagation rule -> alert, et l'agrégation EXACTE servie par /api/coverage/detections.
    use super::*;
    use rusqlite::Connection;

include!("common.rs");
include!("rollup.rs");
include!("detection.rs");
include!("misc.rs");
include!("heartbeat_maintenance.rs"); // P4.1-e : ce qu'une fenêtre de maintenance lève vraiment
include!("ingest.rs");
include!("governance.rs");
include!("engagement.rs");
include!("cases.rs");
include!("incidents.rs");
include!("connectors.rs");
include!("firehose.rs");
include!("pubsub.rs");
include!("tokens.rs");
include!("rbac.rs");
include!("tenants.rs");
include!("sec.rs");
include!("saml.rs");
include!("ai.rs"); // #16 IA conseil — tests TOUS gated `#[cfg(feature="ai")]` en interne (build DÉFAUT = no-op, miroir saml.rs)
include!("soql_completion.rs");
include!("keyset.rs");
include!("query_verify.rs"); // preuve chemin de requête sans perte silencieuse (bornes/regex/joker/combo)
include!("rollup_b2b_adverse.rs"); // B2b (merge rollup ∪ raw) — ajout tests-only
include!("rollup_parity_family.rs"); // parité route rapide == chemin brut, sur une FAMILLE dérivée (pas un cas nommé)
include!("rollup_dim_coverage.rs"); // le JUMEAU : couverture du rollup PAR DIMENSION (trou mesuré, fermeture, garde)
include!("topn_ampleur.rs"); // L'AMPLEUR du plafond top-N (ligne de reste, sonde, aveu) + la rétention qui ferme le résidu ROUTE A
include!("route_a_portes.rs"); // ROUTE A : par quelle porte le sur-compte s'atteindrait — la rétention la ferme, et on le prouve
include!("backup_retention_adverse.rs"); // scheduler backup natif + rétention KEEP-N — tests-only
include!("backup_streaming.rs"); // LE CLAIR SUR DISQUE : staging vide sous surveillance, RAM sous gros BLOB, taille/temps des deux formats
include!("netban.rs"); // chantier ② Phase 1 — ban natif HTTP (IP réelle, store net_ban, guard, API admin)
include!("purge.rs"); // PURGE EXPLICITE d'événements — refus (legal-hold/tier froid/case/FTS), caducité du jeton, registre, dérivés
include!("query_timing.rs"); // la métrique d'attente : garde SANS SEUIL (S permis >= N clients -> attente NULLE) + un seul écrivain
include!("dedup_flotte.rs"); // LA FLOTTE : `event.dedup` cloisonné par hôte (perte silencieuse entre machines)
include!("snapshot_flotte.rs"); // LA FLOTTE (2) : la voie SNAPSHOT — la série est (kind, host)
include!("hotes_muets.rs"); // LA FLOTTE (3) — P3.2-a : un hôte qui se tait ENTIÈREMENT lève un signal. Mutation (19 muets sur 20 : les 21 sondes à portée « tous hôtes confondus » restent vertes, y compris celles qui suivent `pipeline_is_fresh`, lui aussi sans hôte) ET témoin inverse (parc qui parle -> rien). Le coût de l'autre voie — la portée par hôte — est MESURÉ sous mutation du volume x4, et la cardinalité de sortie est prouvée constante en multipliant le parc par 25
include!("sondes_cout.rs"); // P3.7-a : CE QUE COÛTE une sonde de fraîcheur — invariance sous mutation du volume, avec son contre-exemple
include!("transport_liaison.rs"); // TRANSPORT + LIAISON : autorité de la requête (h1/h2), hôte d'une ligne ingérée, portée d'un jeton
include!("panneau_bibliotheque.rs"); // P7.13-a : la porte « SQL brut = admin » du panneau et la définition de bibliothèque
include!("index_redondance.rs"); // P10.2-d : garde DÉRIVÉE des index subsumés — on DEMANDE à SQLite, on n'énumère pas
include!("autoindex_retire.rs"); // P6.8-b : le mécanisme d'auto-index adaptatif est RETIRÉ — garde dérivée anti-zombie + purge de la dette prouvée par mutation
include!("onboarding.rs"); // ONBOARDING /api/setup : d'où sort le token, comment il est comparé/compté, et ce que rend le serveur quand la pose de l'admin N'A PAS été écrite
include!("partition_config.rs"); // P8.7-a : UNE seule voie de lecture des réglages — garde DÉRIVÉE (scanner de sources) + l'annonce de bascule, pure
include!("cle_at_rest_voie_unique.rs"); // P8.7-b : la clé SQLCipher lue par UNE voie — preuve sur les octets (SQLite format 3\0 ou non) + précédence + annonce
include!("barre_fts_vide_silencieux.rs"); // P10.7-a : la barre /api/search rendait « aucun résultat » quand le moteur DISAIT « je refuse » — garde DÉRIVÉE du moteur (balayage ASCII), pas une liste
include!("compactage_fts.rs"); // P10.7-b : une purge fait GROSSIR l'index plein-texte — le défaut mesuré en octets, le correctif, et la mutation (désactivé => l'index reste gonflé au MÊME octet)
include!("index_usage_event.rs"); // P10.D : QUI SE SERT DES INDEX DE `event` — corpus FERMÉ (semeurs + config.d + gabarits) rejoué en EXPLAIN QUERY PLAN, sous deux régimes de statistiques
include!("index_usage_observatoire.rs"); // P10.9-a : L'OBSERVATOIRE D'USAGE DES INDEX — le corpus fermé ne voit ni l'ad hoc analyste ni le régime de statistiques réel ; l'observatoire lit le plan À L'EXÉCUTION, ÉTEINT par défaut (extinction prouvée : exposition VIDE), attribue par classe de consommateur avec une cardinalité plafonnée, et les DEUX témoins sont exigés — un index forcé fait bouger SON compteur et lui seul, un balayage non indexé n'en bouge AUCUN
include!("vieillissement_serie.rs"); // P10.5-a : CE QUE COÛTE UN VIEILLISSEMENT FROID — un succès muet n'est pas une mesure ; « 0 jour traité » ne doit pas ressembler à « je n'ai pas tourné » ; et la crête RSS est ramenée à la FENÊTRE (VmHWM est cumulé depuis le démarrage : c'est le piège dans lequel la mesure du 2026-08-10 est tombée)
include!("cles_de_cause_gardees.rs"); // P10.14-a : TOUTE CLÉ QUI NOMME UN TROU a un test qui la nomme SEULE — garde de SOURCE dérivée (périmètre = qui construit une étiquette `cause` ; clés = le COMPLÉMENT des noms de série), parce que deux lots d'affilée ont livré un chemin `fail-*` gardé par une simple PHRASE
include!("cles_de_roadmap_uniques.rs");
include!("lien_de_recherche_des_alertes.rs"); // P11.1-a : le lien de recherche d'une alerte reproduit son compte — dérivé par le démon (une construction), témoin sur chaque règle livrée avec plancher de règles qui tirent, et témoin négatif sur l'ancienne construction (tête seule + marge)
include!("imputation_de_source.rs"); // S7 : À QUOI UNE ALERTE SE RAPPORTE — l'imputation lue dans la DONNÉE (colonne `event.source`, descripteur de sonde) et non dans la prose de la règle ; mutation dans les deux sens (une source muette -> SA pastille et aucune autre ; deux muettes -> deux pastilles), l'alerte globale intacte, et l'inconnu NOMMÉ plutôt qu'un zéro muet
include!("checkpoint_wal_voie_unique.rs"); // P10.17-a : `wal_checkpoint(TRUNCATE)` rend son verdict par une LIGNE (busy,log,checkpointed), pas par un code d erreur — les 5 sites de production appelaient `execute_batch`, aveugle aux lignes, et croyaient tronquer meme quand un lecteur avait REFUSE. Voie unique + garde qui exclut tests, modules #[cfg(test)] internes et commentaires // P8.9-b : une ligne qui se declare `*(cle neuve)*` doit etre la SEULE definition de sa cle — j'ai ouvert P4.4-j sur une cle DEJA PRISE et je l'ai pousse ; en cherchant la mienne j'ai trouve P8.5-a en double, dont une copie perimee. La regle « une cle = une ligne » a ete REFUTEE par la mesure (6 entrees legitimes accusees) : celle-ci est la regle que le document se donne a lui-meme
include!("tri_en_memoire_voie_unique.rs"); // S26 : la garantie « une connexion qui ne dit rien trie en MÉMOIRE » tenait sur un COMMENTAIRE. SQLCipher ne chiffre pas les temporaires de SQLite : sous l'autre valeur compilée, des valeurs d'événement partiraient EN CLAIR pendant que la bannière annoncerait un déversement désactivé. La valeur est désormais LUE sur le moteur (`compile_options` — `PRAGMA temp_store` rend 0 dans les DEUX mondes et ne prouve rien), la bannière RAPPORTE la lecture, le démarrage REFUSE la valeur dangereuse, et une garde dérivée refuse qu'une connexion s'ouvre hors de la voie qui pose ce réglage — mesuré avant correctif : 23 des 24 chemins d'ouverture de production ne posaient RIEN
include!("enonces_du_vieillissement.rs"); // P10.13-a : LA DÉRIVATION EST-ELLE UNE DÉRIVATION ? — aucun énoncé SQL de lecture ne peut naître hors de `cold_store::enonces`, sinon la sonde `cold-aging-plan` mesurerait une passe qui n'est plus celle qui tourne (garde de SOURCE, catégorie refusée, jamais une liste)
include!("ventilation_serie.rs"); // LA SÉRIE DU BUDGET : la ventilation ÉCRITE DANS LE TEMPS — un refus de mesurer reste un TROU (jamais un zéro), le parcours ne prend pas le verrou d'écriture, et les deux bornes (CPU, disque) sont mesurées
include!("sink_s3.rs"); // SINK OBJET DE L'ORDONNANCEUR DE SAUVEGARDE — tests TOUS gated `#[cfg(feature="s3_backup")]` (build DÉFAUT = no-op, miroir saml.rs/ai.rs) : signature v4 opposée à un oracle TIERS, et les quatre portes par lesquelles un envoi raté pourrait ressortir en succès (refus du service, relecture muette, relecture qui annonce une AUTRE taille, service injoignable)
include!("exercice_de_restauration.rs"); // P8.3-a : L'EXERCICE DE RESTAURATION — une sauvegarde jamais restaurée est une garantie non éprouvée. Restauration menée de bout en bout sur le chemin SYMÉTRIQUE (aucune clé de séquestre n'existe ici, et c'est délibéré), contenu comparé table par table, et l'ABSENCE d'exercice rendue visible et vieillissante. Mutations : archive tronquée, archive parfaite d'une base SANS LIGNE (le cas que l'ancien contrôle rendait vert), horloge avancée
include!("semaphore_interactif.rs"); // P7.8-a : CE QUE COÛTE LA BORNE INTERACTIVE, PAR ROUTE — le décompte des routes qui la consomment est REFAIT à chaque exécution (le constat d'origine en annonçait dix-neuf sans les avoir recomptées), l'attente du permit et le travail permit en main sont mesurés SÉPARÉMENT (un total confond « lente » et « en file », dont les leviers sont opposés), et la cardinalité est bornée deux fois — étiquette = gabarit de route (jamais l'URL), registre plafonné (plafond prouvé en le faisant mordre)
include!("wal_empreinte.rs"); // P10.16-a : L'EMPREINTE DU JOURNAL D'ÉCRITURE — la CRÊTE d'une rafale n'est bornable par aucun réglage (elle dépend des lecteurs qui refusent le point de reprise) ; le RÉSIDU l'est, et c'est lui qu'on porte au budget. Borne DÉRIVÉE (plus gros lot d'ingest + réserve d'auto-checkpoint), témoin négatif sur les deux bras, verdict de la voie unique exercé SOUS la borne, et un seul auteur pour le seuil d'auto-checkpoint
include!("attente_serie.rs"); // P10.11-a : CE QU'UNE PASSE DE VIEILLISSEMENT COÛTE À UN ANALYSTE — l'attente était rendue DANS LA RÉPONSE d'une requête, donc corrélable par rien. La distribution a été MESURÉE avant de choisir la forme : la moyenne sous-estime le pire échantillon d'un facteur 73 et le p99 lui-même est AVEUGLE au régime le plus proche de l'exploitation, donc des SEAUX et un MAXIMUM (qui survivent au rollup horaire, ce qu'un quantile ne fait pas). Mutation dans les deux sens, concentration « une requête sur cent » opposée à ce qu'une moyenne en aurait dit, composition permis+verrou opposée au temps mural, et la fenêtre de la passe lisible sur la MÊME échelle de temps
include!("maj_corroboree.rs"); // P5.7-b : LE SOC S'ALERTE SUR SA PROPRE MISE À JOUR — un dépôt d'unité systemd n'est reclassé que si son CONTENU est l'une des 88 unités que CE build livre, sous le nom sous lequel elle est livrée, ET dans la fenêtre bornée qu'ouvre un déploiement daté et audité. Aucune exemption par nom : le nom ne peut que RESTREINDRE. Mutation dans les deux sens, dont un dépôt hostile sous six formes (nom du produit + contenu étranger, nom inventé, contenu livré sous un autre nom, hors fenêtre, antérieur au déploiement, sans déploiement) qui restent TOUS détectés ; et l'événement n'est jamais effacé — il descend en informationnel et gagne son motif et sa sévérité d'origine
include!("mesure_environnement.rs"); // S32 : UNE MESURE D'ENVIRONNEMENT QUI ÉCHOUE NE REND PAS LA VALEUR LA PLUS RASSURANTE — un répertoire de spool disparu se lisait « file vide » et un `/proc` muet publiait « aucun temps processeur, aucune mémoire résidente ». Chaque propriété est tenue par une PAIRE de témoins (source retirée -> `illisible` + cause nommée + AUCUN nombre ; source présente valant réellement zéro -> `lu` + 0), parce que le premier sens seul serait passé par une fonction qui ne saurait jamais rien. Fonctions paramétrées sur leur racine et sur les constantes de l'hôte : le même verdict tombe avec ou sans `/proc`
include!("allegations_d_environnement.rs"); // S29 : UNE PROPRIÉTÉ D'ENVIRONNEMENT AFFIRMÉE EN PROSE N'A AUCUN MOYEN DE VIEILLIR — le recensement rend 258 phrases qui affirment un comportement de bac à sable, de système de fichiers ou de noyau, dont un quart seulement porte une date. Le tri est fait sur le SILENCE PRODUIT (« que se passe-t-il si ça cesse d'être vrai, et qui l'apprend ? ») et non sur le nombre : sont tenues ici les quatre allégations dont la fausseté laisserait le système rendre une valeur RASSURANTE — aucun journal de requêtes monté (donc un secret en query-string qui ne fuit pas), aucun collecteur dans le namespace de contrôle (donc aucun capteur muet par renommage), le capteur d'intégrité qui hache toujours le répertoire d'unités (donc une règle de persistance qui peut encore lever), et l'unité du démon sans EnvironmentFile (donc pas de clé SQLCipher lisible dans l'environnement du processus). Les quatre lisent le FICHIER que la phrase prend à témoin, jamais la phrase ; chacune exige un témoin positif ET un témoin négatif avant de conclure, et le dépouillement commentaires+chaînes est lui-même prouvé dans les deux sens
include!("banniere_de_deversement_mesuree.rs"); // S38 : LA BANNIÈRE DE DÉVERSEMENT MESURE UNE CONNEXION ARMÉE — elle lisait une sonde NUE, sur laquelle personne ne pose `temp_store=FILE`, donc sous `PLUME_SQLITE_DEVERSEMENT=1` elle contredisait le mode à CHAQUE démarrage (« demandé mais tri en mémoire, local=0 ») ; une garde qui alerte toujours ne prouve rien et apprend à ne plus la lire. La mesure est désormais LUE sur la connexion qui sert, rendue sous la forme de S32 (« NON MESURÉ » quand aucune connexion armée n'est là, jamais la lecture d'une autre connexion), et les DEUX couples réels sont joués sur une vraie base armée par la voie unique paramétrée sur le mode : demandé et TENU, demandé et contredit par une connexion volontairement non armée ; témoin inverse : sans mesure, jamais « tenu »
include!("branche_d_echec_muette.rs"); // P4.1-r : UNE BRANCHE D'ÉCHEC MUETTE HORS DU CRATE DE L'AGENT — ce que les sites fermés RENDENT quand la source manque (listing refusé, élagage refusé sans rien supprimer, tick aveugle, fichier de spool indécodable en quarantaine, balayage et inventaire qui comptent leurs illisibles) et ce qu'ils rendent quand elle est saine (un VRAI zéro) ; la privation de droits est VALIDÉE avant d'être comptée, et un plancher de familles refuse de conclure à vide
include!("posture_de_sauvegarde_native.rs"); // P8.25-a + P8.26-a : LES SIGNAUX DE POSTURE SUIVENT L'ARCHIVE SUR LE CHEMIN NATIF — « sauvegarde symétrique : aucun destinataire d'escrow » et « restauration non éprouvée » n'avaient qu'un appelant (la sous-commande) ; le cycle natif, celui que `deploy/k3s.yaml` active, publiait des archives déchiffrables par le nœud et jamais restaurées avec pour seul témoin une ligne de journal. Trois témoins par signal (sans destinataire / sans exercice -> un signal non purgeable, dédupliqué à l'heure / au jour ; avec destinataire / exercice frais -> rien ; cycle qui échoue, refusé OU produit-mais-jamais-publié -> rien) et UNE garde DÉRIVÉE des appelants de ce qui écrit l'archive et des racines `signal_*`, qui exige que tout écrivain atteigne TOUS les signaux
include!("couverture_attack_nommee.rs"); // P11.6-a : UNE TECHNIQUE ATT&CK NE SE LIT PAS PAR SON SEUL NUMÉRO — la matrice servait 183 identifiants sans nom (le champ `name` n'était jamais émis) ; le nom est dérivé de l'identifiant (sous-technique -> « Parent : sous-technique », sinon parent), la population des témoins est le catalogue du cœur ET les techniques citées par les règles livrées (seeds + config.d), et le seul identifiant sans nom est celui hors catalogue, rendu `null` pour que la surface dise « nom inconnu »
include!("reponse_lisible_et_destination.rs"); // P11.2-b + P11.1-e : UN INTERRUPTEUR QUI ARME UN BAN SE LIT, ET CE QUI CRÉE UN PRODUCTEUR D'ALERTES DIT OÙ IL ARRIVE — la phrase de conséquence d'un ban_ip est confrontée à la durée que les exécuteurs posent (argv CrowdSec, TTL du blocage natif) ; le vocabulaire d'actions est lu dans les surfaces web ; la liste des playbooks porte la phrase et le mode courant (mutation observe -> active) ; garde DÉRIVÉE : tables de producteurs lues dans les boucles du planificateur, routes créatrices lues dans server.rs + corps des handlers (insertion directe ou déléguée), modules web qui POSTent dessus lus sous web/ — chacun nomme la destination, et les écarts connus sont nommés avec leur raison
include!("sources_attendues_et_cadence.rs"); // P11.3-a + P11.3-b : LE VERDICT « INATTENDU » EST DÉRIVÉ DES FICHIERS LIVRÉS (six des sept sources du constat étaient émises par un collecteur livré — défaut de dérivation, pas de bouton), le marquage « attendue » est editor+, persistant, réversible, audité et rendu avec son auteur, un libellé n'acquitte plus rien en silence ; la CADENCE ATTENDUE est celle que les sondes DÉCLARENT (plus une moyenne observée), le statut en dérive côté démon (muet / en retard / frais / calme — « dégradé » disparaît, les alertes actives sont un compte), et l'inventaire rend le même mot que la fraîcheur
include!("suppressions_trois_gestes.rs"); // P11.5-a : LES TROIS GESTES DE L'ADMINISTRATEUR SUR UN SILENCE — la modification (PUT /api/silences/:id) rejoint création et levée avec la même classe de rôle et le même audit fail-closed ; preuve par MUTATION du ledger et des events plume-config, témoin négatif (corps invalide -> rien n'écrit, rien d'audité), et un enregistrement sans changement qui n'est pas un événement
include!("filtre_source_des_alertes.rs"); // P11.1-b : LE FILTRE `source` DES ALERTES EST UN PRÉDICAT D'IMPUTATION EXACT, CÔTÉ SERVEUR — un nom ENTIER de `alert.sources` (`k8s` ne prend pas `k8s-audit`, ni `audit-k8s`, ni `K8S`), dérivé du séparateur de l'encodeur ; le mutant `LIKE` est joué sur la même fixture et prend les trois voisins ; composition avec statut/technique/hors case, routes groupées (compte, aperçu re-scopé, expansion), valeur hors borne refusée en 400 par le routeur réel, et la limite nommée (une alerte d'avant la migration n'est appariée à rien)
include!("detection_aveugle.rs"); // P3.9-a : UNE RÈGLE ABANDONNÉE À RÉPÉTITION LÈVE UNE ALERTE — la cause de l'abandon est CONSERVÉE (ensemble fermé : budget dépassé, erreur de requête, non numérique, compilation refusée, fil en panique) là où un seul `None` les fondait, le compte consécutif par règle PERSISTE (v116) et se remet à zéro à la première réussite, et au seuil DÉRIVÉ de l'intervalle (une heure d'horizon, plancher deux) une alerte « détection aveugle : <règle> — <cause>, N évaluations » par le chemin des alertes de capteur muet, dédupliquée par règle, résolue au retour ; témoins : N−1 -> rien, N -> une seule, succès -> résolue et clé libérée, deux règles -> deux alertes, migration additive et convergente ; garde DÉRIVÉE : tout évaluateur qui compte des abandons et lit `rule` consigne, ou est nommé comme écart
