    //! Tests de la mesure de couverture de détection (purple-team, blue-team value) : migration MITRE
    //! idempotente, propagation rule -> alert, et l'agrégation EXACTE servie par /api/coverage/detections.
    use super::*;
    use rusqlite::Connection;

include!("common.rs");
include!("rollup.rs");
include!("detection.rs");
include!("misc.rs");
include!("heartbeat_maintenance.rs"); // P4.1-e : ce qu'une fenêtre de maintenance lève vraiment
include!("ingest.rs");
include!("governance.rs");
include!("engagement.rs");
include!("cases.rs");
include!("incidents.rs");
include!("connectors.rs");
include!("firehose.rs");
include!("pubsub.rs");
include!("tokens.rs");
include!("rbac.rs");
include!("tenants.rs");
include!("sec.rs");
include!("saml.rs");
include!("ai.rs"); // #16 IA conseil — tests TOUS gated `#[cfg(feature="ai")]` en interne (build DÉFAUT = no-op, miroir saml.rs)
include!("soql_completion.rs");
include!("keyset.rs");
include!("query_verify.rs"); // preuve chemin de requête sans perte silencieuse (bornes/regex/joker/combo)
include!("rollup_b2b_adverse.rs"); // B2b (merge rollup ∪ raw) — ajout tests-only
include!("rollup_parity_family.rs"); // parité route rapide == chemin brut, sur une FAMILLE dérivée (pas un cas nommé)
include!("rollup_dim_coverage.rs"); // le JUMEAU : couverture du rollup PAR DIMENSION (trou mesuré, fermeture, garde)
include!("topn_ampleur.rs"); // L'AMPLEUR du plafond top-N (ligne de reste, sonde, aveu) + la rétention qui ferme le résidu ROUTE A
include!("route_a_portes.rs"); // ROUTE A : par quelle porte le sur-compte s'atteindrait — la rétention la ferme, et on le prouve
include!("backup_retention_adverse.rs"); // scheduler backup natif + rétention KEEP-N — tests-only
include!("backup_streaming.rs"); // LE CLAIR SUR DISQUE : staging vide sous surveillance, RAM sous gros BLOB, taille/temps des deux formats
include!("netban.rs");
include!("identite_d_adresse.rs"); // P4.7-g/h/i/j/k : L'IDENTITÉ D'UNE ADRESSE EST SA VALEUR — propriété métamorphique engendrée depuis le corpus partagé (aucune paire écrite), largeur protégée DÉRIVÉE de l'arithmétique du masque avec ses quatre bornes, le contrat « toute cible de ban s'analyse » qui autorise le refus d'analyse à ne PAS valoir « protégée », la levée de ban qui DIT ce qu'elle a retiré, et l'identité de valeur du pair TCP // chantier ② Phase 1 — ban natif HTTP (IP réelle, store net_ban, guard, API admin)
include!("purge.rs"); // PURGE EXPLICITE d'événements — refus (legal-hold/tier froid/case/FTS), caducité du jeton, registre, dérivés
include!("query_timing.rs"); // la métrique d'attente : garde SANS SEUIL (S permis >= N clients -> attente NULLE) + un seul écrivain
include!("dedup_flotte.rs"); // LA FLOTTE : `event.dedup` cloisonné par hôte (perte silencieuse entre machines)
include!("snapshot_flotte.rs"); // LA FLOTTE (2) : la voie SNAPSHOT — la série est (kind, host)
include!("hotes_muets.rs"); // LA FLOTTE (3) — P3.2-a : un hôte qui se tait ENTIÈREMENT lève un signal. Mutation (19 muets sur 20 : les 21 sondes à portée « tous hôtes confondus » restent vertes, y compris celles qui suivent `pipeline_is_fresh`, lui aussi sans hôte) ET témoin inverse (parc qui parle -> rien). Le coût de l'autre voie — la portée par hôte — est MESURÉ sous mutation du volume x4, et la cardinalité de sortie est prouvée constante en multipliant le parc par 25
include!("hotes_declares.rs"); // LA FLOTTE (4) — P11.10-a : CE QU'ON ATTEND D'UN HÔTE SE DÉCLARE, et le compte cesse de mélanger. La grammaire de P11.3-c transposée (déclarant nommé, date, colonnes propres, « quelqu'un a dit non » distinct de « personne n'a rien dit »), le défaut par défaut INVERSÉ et dit ; deux mutations qui nomment la valeur qui change (silence attendu -> `muets` baisse, `attendus` NON ; retiré -> les deux baissent), témoin négatif sur la phrase de non-couverture, parts publiées qui FONT LE TOUT et comptent la MÊME population que la sonde, motif EXIGÉ là où le geste éteint (chemin fermé, 400), et la table supprimée qui fait alerter PLUS et jamais moins
include!("sondes_cout.rs"); // P3.7-a : CE QUE COÛTE une sonde de fraîcheur — invariance sous mutation du volume, avec son contre-exemple
include!("transport_liaison.rs"); // TRANSPORT + LIAISON : autorité de la requête (h1/h2), hôte d'une ligne ingérée, portée d'un jeton
include!("panneau_bibliotheque.rs"); // P7.13-a : la porte « SQL brut = admin » du panneau et la définition de bibliothèque
include!("index_redondance.rs"); // P10.2-d : garde DÉRIVÉE des index subsumés — on DEMANDE à SQLite, on n'énumère pas
include!("autoindex_retire.rs"); // P6.8-b : le mécanisme d'auto-index adaptatif est RETIRÉ — garde dérivée anti-zombie + purge de la dette prouvée par mutation
include!("onboarding.rs"); // ONBOARDING /api/setup : d'où sort le token, comment il est comparé/compté, et ce que rend le serveur quand la pose de l'admin N'A PAS été écrite
include!("partition_config.rs"); // P8.7-a : UNE seule voie de lecture des réglages — garde DÉRIVÉE (scanner de sources) + l'annonce de bascule, pure
include!("cle_at_rest_voie_unique.rs"); // P8.7-b : la clé SQLCipher lue par UNE voie — preuve sur les octets (SQLite format 3\0 ou non) + précédence + annonce
include!("base_neuve_nait_chiffree.rs"); // P9.6-a : une base NEUVE naît CHIFFRÉE, une base EXISTANTE n'est JAMAIS touchée par un démarrage, et une base existante ne se chiffre que par un GESTE explicite. Le témoin qui compte le plus est le deuxième — les octets ENTIERS d'une base en clair, inchangés sur trois démarrages, avec sa mutation dans le même corps (base absente -> la clé EST engendrée) sans quoi l'immobilité ne prouverait rien. La propriété « base neuve » exige DEUX absences indépendantes (fichier principal ET compagnons SQLite) et toute mesure qui échoue ne conclut pas (S32). La clé est posée 0600 à la CRÉATION et ses droits sont RELUS ; elle n'est jamais réécrite (create_new). L'oubli de la mettre à l'abri est dit par un signal NON PURGEABLE — prouvé par le prédicat de purge du produit, pas par une liste recopiée — et jamais par une simple ligne de journal, ce qui est précisément ce qui a échoué pour la sauvegarde muette. Le geste de conversion prouve l'équivalence (integrity_check, empreinte sqlite_master dans les deux sens, compte de CHAQUE table, chaîne du journal inaltérable), produit une archive VÉRIFIÉE PAR RESTAURATION avant de basculer, bascule par un SEUL rename, s'inscrit au journal, et son échec laisse l'original intact sans aucun état intermédiaire démarrable
include!("barre_fts_vide_silencieux.rs"); // P10.7-a : la barre /api/search rendait « aucun résultat » quand le moteur DISAIT « je refuse » — garde DÉRIVÉE du moteur (balayage ASCII), pas une liste
include!("compactage_fts.rs"); // P10.7-b : une purge fait GROSSIR l'index plein-texte — le défaut mesuré en octets, le correctif, et la mutation (désactivé => l'index reste gonflé au MÊME octet)
include!("index_usage_event.rs"); // P10.D : QUI SE SERT DES INDEX DE `event` — corpus FERMÉ (semeurs + config.d + gabarits) rejoué en EXPLAIN QUERY PLAN, sous deux régimes de statistiques
include!("index_usage_observatoire.rs"); // P10.9-a : L'OBSERVATOIRE D'USAGE DES INDEX — le corpus fermé ne voit ni l'ad hoc analyste ni le régime de statistiques réel ; l'observatoire lit le plan À L'EXÉCUTION, ÉTEINT par défaut (extinction prouvée : exposition VIDE), attribue par classe de consommateur avec une cardinalité plafonnée, et les DEUX témoins sont exigés — un index forcé fait bouger SON compteur et lui seul, un balayage non indexé n'en bouge AUCUN
include!("vieillissement_serie.rs"); // P10.5-a : CE QUE COÛTE UN VIEILLISSEMENT FROID — un succès muet n'est pas une mesure ; « 0 jour traité » ne doit pas ressembler à « je n'ai pas tourné » ; et la crête RSS est ramenée à la FENÊTRE (VmHWM est cumulé depuis le démarrage : c'est le piège dans lequel la mesure du 2026-08-10 est tombée)
include!("cles_de_cause_gardees.rs"); // P10.14-a : TOUTE CLÉ QUI NOMME UN TROU a un test qui la nomme SEULE — garde de SOURCE dérivée (périmètre = qui construit une étiquette `cause` ; clés = le COMPLÉMENT des noms de série), parce que deux lots d'affilée ont livré un chemin `fail-*` gardé par une simple PHRASE
include!("cles_de_roadmap_uniques.rs");
include!("lien_de_recherche_des_alertes.rs"); // P11.1-a : le lien de recherche d'une alerte reproduit son compte — dérivé par le démon (une construction), témoin sur chaque règle livrée avec plancher de règles qui tirent, et témoin négatif sur l'ancienne construction (tête seule + marge)
include!("machine_dune_alerte.rs"); // P11.18-v : la MACHINE d'une alerte est SERVIE — la colonne était liée à l'écriture par quatre voies de levée et absente de l'énoncé qui sert la file. Trois faits servis DISTINCTEMENT (nom / chaîne vide = machine INCONNUE / `null` = aucune machine liée), avec le CONTRÔLE POSITIF sans lequel un `null` se confondrait avec une clé absente, la MUTATION qui montre ce que le COALESCE de l'axe de tri détruit, et le SURCOÛT du corps servi mesuré par différence sur la même page, borné par une formule dérivée
include!("imputation_de_source.rs"); // S7 : À QUOI UNE ALERTE SE RAPPORTE — l'imputation lue dans la DONNÉE (colonne `event.source`, descripteur de sonde) et non dans la prose de la règle ; mutation dans les deux sens (une source muette -> SA pastille et aucune autre ; deux muettes -> deux pastilles), l'alerte globale intacte, et l'inconnu NOMMÉ plutôt qu'un zéro muet
include!("checkpoint_wal_voie_unique.rs"); // P10.17-a : `wal_checkpoint(TRUNCATE)` rend son verdict par une LIGNE (busy,log,checkpointed), pas par un code d erreur — les 5 sites de production appelaient `execute_batch`, aveugle aux lignes, et croyaient tronquer meme quand un lecteur avait REFUSE. Voie unique + garde qui exclut tests, modules #[cfg(test)] internes et commentaires // P8.9-b : une ligne qui se declare `*(cle neuve)*` doit etre la SEULE definition de sa cle — j'ai ouvert P4.4-j sur une cle DEJA PRISE et je l'ai pousse ; en cherchant la mienne j'ai trouve P8.5-a en double, dont une copie perimee. La regle « une cle = une ligne » a ete REFUTEE par la mesure (6 entrees legitimes accusees) : celle-ci est la regle que le document se donne a lui-meme
include!("tri_en_memoire_voie_unique.rs"); // S26 : la garantie « une connexion qui ne dit rien trie en MÉMOIRE » tenait sur un COMMENTAIRE. SQLCipher ne chiffre pas les temporaires de SQLite : sous l'autre valeur compilée, des valeurs d'événement partiraient EN CLAIR pendant que la bannière annoncerait un déversement désactivé. La valeur est désormais LUE sur le moteur (`compile_options` — `PRAGMA temp_store` rend 0 dans les DEUX mondes et ne prouve rien), la bannière RAPPORTE la lecture, le démarrage REFUSE la valeur dangereuse, et une garde dérivée refuse qu'une connexion s'ouvre hors de la voie qui pose ce réglage — mesuré avant correctif : 23 des 24 chemins d'ouverture de production ne posaient RIEN
include!("enonces_du_vieillissement.rs"); // P10.13-a : LA DÉRIVATION EST-ELLE UNE DÉRIVATION ? — aucun énoncé SQL de lecture ne peut naître hors de `cold_store::enonces`, sinon la sonde `cold-aging-plan` mesurerait une passe qui n'est plus celle qui tourne (garde de SOURCE, catégorie refusée, jamais une liste)
include!("ventilation_serie.rs"); // LA SÉRIE DU BUDGET : la ventilation ÉCRITE DANS LE TEMPS — un refus de mesurer reste un TROU (jamais un zéro), le parcours ne prend pas le verrou d'écriture, et les deux bornes (CPU, disque) sont mesurées
include!("sink_s3.rs"); // SINK OBJET DE L'ORDONNANCEUR DE SAUVEGARDE — tests TOUS gated `#[cfg(feature="s3_backup")]` (build DÉFAUT = no-op, miroir saml.rs/ai.rs) : signature v4 opposée à un oracle TIERS, et les quatre portes par lesquelles un envoi raté pourrait ressortir en succès (refus du service, relecture muette, relecture qui annonce une AUTRE taille, service injoignable)
include!("exercice_de_restauration.rs"); // P8.3-a : L'EXERCICE DE RESTAURATION — une sauvegarde jamais restaurée est une garantie non éprouvée. Restauration menée de bout en bout sur le chemin SYMÉTRIQUE (aucune clé de séquestre n'existe ici, et c'est délibéré), contenu comparé table par table, et l'ABSENCE d'exercice rendue visible et vieillissante. Mutations : archive tronquée, archive parfaite d'une base SANS LIGNE (le cas que l'ancien contrôle rendait vert), horloge avancée
include!("semaphore_interactif.rs"); // P7.8-a : CE QUE COÛTE LA BORNE INTERACTIVE, PAR ROUTE — le décompte des routes qui la consomment est REFAIT à chaque exécution (le constat d'origine en annonçait dix-neuf sans les avoir recomptées), l'attente du permit et le travail permit en main sont mesurés SÉPARÉMENT (un total confond « lente » et « en file », dont les leviers sont opposés), et la cardinalité est bornée deux fois — étiquette = gabarit de route (jamais l'URL), registre plafonné (plafond prouvé en le faisant mordre)
include!("wal_empreinte.rs"); // P10.16-a : L'EMPREINTE DU JOURNAL D'ÉCRITURE — la CRÊTE d'une rafale n'est bornable par aucun réglage (elle dépend des lecteurs qui refusent le point de reprise) ; le RÉSIDU l'est, et c'est lui qu'on porte au budget. Borne DÉRIVÉE (plus gros lot d'ingest + réserve d'auto-checkpoint), témoin négatif sur les deux bras, verdict de la voie unique exercé SOUS la borne, et un seul auteur pour le seuil d'auto-checkpoint
include!("attente_serie.rs"); // P10.11-a : CE QU'UNE PASSE DE VIEILLISSEMENT COÛTE À UN ANALYSTE — l'attente était rendue DANS LA RÉPONSE d'une requête, donc corrélable par rien. La distribution a été MESURÉE avant de choisir la forme : la moyenne sous-estime le pire échantillon d'un facteur 73 et le p99 lui-même est AVEUGLE au régime le plus proche de l'exploitation, donc des SEAUX et un MAXIMUM (qui survivent au rollup horaire, ce qu'un quantile ne fait pas). Mutation dans les deux sens, concentration « une requête sur cent » opposée à ce qu'une moyenne en aurait dit, composition permis+verrou opposée au temps mural, et la fenêtre de la passe lisible sur la MÊME échelle de temps
include!("maj_corroboree.rs"); // P5.7-b : LE SOC S'ALERTE SUR SA PROPRE MISE À JOUR — un dépôt d'unité systemd n'est reclassé que si son CONTENU est l'une des 88 unités que CE build livre, sous le nom sous lequel elle est livrée, ET dans la fenêtre bornée qu'ouvre un déploiement daté et audité. Aucune exemption par nom : le nom ne peut que RESTREINDRE. Mutation dans les deux sens, dont un dépôt hostile sous six formes (nom du produit + contenu étranger, nom inventé, contenu livré sous un autre nom, hors fenêtre, antérieur au déploiement, sans déploiement) qui restent TOUS détectés ; et l'événement n'est jamais effacé — il descend en informationnel et gagne son motif et sa sévérité d'origine
include!("mesure_environnement.rs"); // S32 : UNE MESURE D'ENVIRONNEMENT QUI ÉCHOUE NE REND PAS LA VALEUR LA PLUS RASSURANTE — un répertoire de spool disparu se lisait « file vide » et un `/proc` muet publiait « aucun temps processeur, aucune mémoire résidente ». Chaque propriété est tenue par une PAIRE de témoins (source retirée -> `illisible` + cause nommée + AUCUN nombre ; source présente valant réellement zéro -> `lu` + 0), parce que le premier sens seul serait passé par une fonction qui ne saurait jamais rien. Fonctions paramétrées sur leur racine et sur les constantes de l'hôte : le même verdict tombe avec ou sans `/proc`
include!("allegations_d_environnement.rs"); // S29 : UNE PROPRIÉTÉ D'ENVIRONNEMENT AFFIRMÉE EN PROSE N'A AUCUN MOYEN DE VIEILLIR — le recensement rend 258 phrases qui affirment un comportement de bac à sable, de système de fichiers ou de noyau, dont un quart seulement porte une date. Le tri est fait sur le SILENCE PRODUIT (« que se passe-t-il si ça cesse d'être vrai, et qui l'apprend ? ») et non sur le nombre : sont tenues ici les quatre allégations dont la fausseté laisserait le système rendre une valeur RASSURANTE — aucun journal de requêtes monté (donc un secret en query-string qui ne fuit pas), aucun collecteur dans le namespace de contrôle (donc aucun capteur muet par renommage), le capteur d'intégrité qui hache toujours le répertoire d'unités (donc une règle de persistance qui peut encore lever), et l'unité du démon sans EnvironmentFile (donc pas de clé SQLCipher lisible dans l'environnement du processus). Les quatre lisent le FICHIER que la phrase prend à témoin, jamais la phrase ; chacune exige un témoin positif ET un témoin négatif avant de conclure, et le dépouillement commentaires+chaînes est lui-même prouvé dans les deux sens
include!("banniere_de_deversement_mesuree.rs"); // S38 : LA BANNIÈRE DE DÉVERSEMENT MESURE UNE CONNEXION ARMÉE — elle lisait une sonde NUE, sur laquelle personne ne pose `temp_store=FILE`, donc sous `PLUME_SQLITE_DEVERSEMENT=1` elle contredisait le mode à CHAQUE démarrage (« demandé mais tri en mémoire, local=0 ») ; une garde qui alerte toujours ne prouve rien et apprend à ne plus la lire. La mesure est désormais LUE sur la connexion qui sert, rendue sous la forme de S32 (« NON MESURÉ » quand aucune connexion armée n'est là, jamais la lecture d'une autre connexion), et les DEUX couples réels sont joués sur une vraie base armée par la voie unique paramétrée sur le mode : demandé et TENU, demandé et contredit par une connexion volontairement non armée ; témoin inverse : sans mesure, jamais « tenu »
include!("branche_d_echec_muette.rs"); // P4.1-r : UNE BRANCHE D'ÉCHEC MUETTE HORS DU CRATE DE L'AGENT — ce que les sites fermés RENDENT quand la source manque (listing refusé, élagage refusé sans rien supprimer, tick aveugle, fichier de spool indécodable en quarantaine, balayage et inventaire qui comptent leurs illisibles) et ce qu'ils rendent quand elle est saine (un VRAI zéro) ; la privation de droits est VALIDÉE avant d'être comptée, et un plancher de familles refuse de conclure à vide
include!("etat_vivant_jamais_remplace_par_vide.rs"); // P10.7-k : une lecture ratée ne remplace pas un état VIVANT par un état VIDE — le cache de correspondance IOC (une DÉTECTION qui s'éteint sans qu'aucun corps servi ne le dise), le dénominateur d'hôtes du panneau des suppressions, et la politique de redaction servie comme la vôtre. Trois temps par propriété (saine -> illisible -> saine à nouveau), le compte CONSERVÉ dans l'aveu, et la borne STRUCTURELLE : `Mesure::valeur()` rend `Option`, donc aucun appelant ne peut publier le nombre rassurant
include!("posture_de_sauvegarde_native.rs"); // P8.25-a + P8.26-a : LES SIGNAUX DE POSTURE SUIVENT L'ARCHIVE SUR LE CHEMIN NATIF — « sauvegarde symétrique : aucun destinataire d'escrow » et « restauration non éprouvée » n'avaient qu'un appelant (la sous-commande) ; le cycle natif, celui que `deploy/k3s.yaml` active, publiait des archives déchiffrables par le nœud et jamais restaurées avec pour seul témoin une ligne de journal. Trois témoins par signal (sans destinataire / sans exercice -> un signal non purgeable, dédupliqué à l'heure / au jour ; avec destinataire / exercice frais -> rien ; cycle qui échoue, refusé OU produit-mais-jamais-publié -> rien) et UNE garde DÉRIVÉE des appelants de ce qui écrit l'archive et des racines `signal_*`, qui exige que tout écrivain atteigne TOUS les signaux
include!("couverture_attack_nommee.rs"); // P11.6-a : UNE TECHNIQUE ATT&CK NE SE LIT PAS PAR SON SEUL NUMÉRO — la matrice servait 183 identifiants sans nom (le champ `name` n'était jamais émis) ; le nom est dérivé de l'identifiant (sous-technique -> « Parent : sous-technique », sinon parent), la population des témoins est le catalogue du cœur ET les techniques citées par les règles livrées (seeds + config.d), et le seul identifiant sans nom est celui hors catalogue, rendu `null` pour que la surface dise « nom inconnu »
include!("reponse_lisible_et_destination.rs"); // P11.2-b + P11.1-e : UN INTERRUPTEUR QUI ARME UN BAN SE LIT, ET CE QUI CRÉE UN PRODUCTEUR D'ALERTES DIT OÙ IL ARRIVE — la phrase de conséquence d'un ban_ip est confrontée à la durée que les exécuteurs posent (argv CrowdSec, TTL du blocage natif) ; le vocabulaire d'actions est lu dans les surfaces web ; la liste des playbooks porte la phrase et le mode courant (mutation observe -> active) ; garde DÉRIVÉE : tables de producteurs lues dans les boucles du planificateur, routes créatrices lues dans le module `server` + corps des handlers (insertion directe ou déléguée), modules web qui POSTent dessus lus sous web/ — chacun nomme la destination, et les écarts connus sont nommés avec leur raison
include!("sources_attendues_et_cadence.rs"); // P11.3-a + P11.3-b : LE VERDICT « INATTENDU » EST DÉRIVÉ DES FICHIERS LIVRÉS (six des sept sources du constat étaient émises par un collecteur livré — défaut de dérivation, pas de bouton), le marquage « attendue » est editor+, persistant, réversible, audité et rendu avec son auteur, un libellé n'acquitte plus rien en silence ; la CADENCE ATTENDUE est celle que les sondes DÉCLARENT (plus une moyenne observée), le statut en dérive côté démon (muet / en retard / frais / calme — « dégradé » disparaît, les alertes actives sont un compte), et l'inventaire rend le même mot que la fraîcheur
include!("suppressions_trois_gestes.rs"); // P11.5-a : LES TROIS GESTES DE L'ADMINISTRATEUR SUR UN SILENCE — la modification (PUT /api/silences/{id}) rejoint création et levée avec la même classe de rôle et le même audit fail-closed ; preuve par MUTATION du ledger et des events plume-config, témoin négatif (corps invalide -> rien n'écrit, rien d'audité), et un enregistrement sans changement qui n'est pas un événement
include!("filtre_source_des_alertes.rs"); // P11.1-b : LE FILTRE `source` DES ALERTES EST UN PRÉDICAT D'IMPUTATION EXACT, CÔTÉ SERVEUR — un nom ENTIER de `alert.sources` (`k8s` ne prend pas `k8s-audit`, ni `audit-k8s`, ni `K8S`), dérivé du séparateur de l'encodeur ; le mutant `LIKE` est joué sur la même fixture et prend les trois voisins ; composition avec statut/technique/hors case, routes groupées (compte, aperçu re-scopé, expansion), valeur hors borne refusée en 400 par le routeur réel, et la limite nommée (une alerte d'avant la migration n'est appariée à rien)
include!("detection_aveugle.rs"); // P3.9-a : UNE RÈGLE ABANDONNÉE À RÉPÉTITION LÈVE UNE ALERTE — la cause de l'abandon est CONSERVÉE (ensemble fermé : budget dépassé, erreur de requête, non numérique, compilation refusée, fil en panique) là où un seul `None` les fondait, le compte consécutif par règle PERSISTE (v116) et se remet à zéro à la première réussite, et au seuil DÉRIVÉ de l'intervalle (une heure d'horizon, plancher deux) une alerte « détection aveugle : <règle> — <cause>, N évaluations » par le chemin des alertes de capteur muet, dédupliquée par règle, résolue au retour ; témoins : N−1 -> rien, N -> une seule, succès -> résolue et clé libérée, deux règles -> deux alertes, migration additive et convergente ; garde DÉRIVÉE : tout évaluateur qui compte des abandons et lit `rule` consigne, ou est nommé comme écart | P9.5-a : L'AUTRE EXTINCTION — une règle qui s'évalue très bien et rend zéro POUR TOUJOURS parce qu'aucun producteur livré n'émet la source qu'elle épingle (aucun abandon à consigner, rien à distinguer d'un hôte sain), alors que la matrice ATT&CK compte sa technique COUVERTE ; le critère est DÉRIVÉ (épinglages positifs et littéraux de `source` lus dans la requête × `SOURCES_LIVREES` + sondes `COLLECTORS`, « le produit l'AGRÈGE » explicitement exclu), jamais une liste de noms ; témoins : l'extracteur validé positif/négatif hors base (citation, glob, motif, négation, `by source`, `cf_source`), le verdict rendu sur la base qu'une installation FRAÎCHE reçoit (semis EXÉCUTÉ, pas relu) dans les DEUX sens, et la conséquence tenue à l'autre bout, en TROIS états et non deux : la technique d'une règle activée que rien ne nourrit n'est ni annoncée couverte, ni effacée, NI CONFONDUE AVEC UN ANGLE MORT — elle est comptée à part AVEC SA RAISON (les sources qui manquent), et un vrai angle mort du même catalogue sert de témoin négatif ; la jambe qui affirmait « rendue comme angle mort » était une TAUTOLOGIE (toute technique à zéro règle la satisfait) et elle a été retirée ; l'import Sigma compte ses deux membres de la MÊME manière, sans quoi la différence est gonflée d'exactement ce que le filtre retire du « avant »
include!("sauvegarde_preschema.rs"); // P4.4-l : LA SAUVEGARDE NOMMÉE D'AVANT UN FRANCHISSEMENT DE SCHÉMA — `plume-<TS>-preschema<N>.db.age`, prise à chaud par l'outil de l'exploitant et déposée à la racine du préfixe, arrivait dans `backup-prune-plan` comme `Unparseable` : jamais proposée, un objet de plus par franchissement, à jamais. Classe `PreSchema { ts, schema }` dans le SEUL analyseur, même règle que `premigrate` (N plus récents, même réglage), quotas SÉPARÉS prouvés par mutation (rangée dans `Premigrate` ou `Regular`, un témoin rougit), voisins refusés, idempotence, et l'ordonnanceur natif qui ne la touche pas
include!("comptes_qui_accedent.rs");
include!("requete_reutilisable_de_regle.rs"); // P11.13-a : LA REQUÊTE D'UNE RÈGLE, RENDUE RÉUTILISABLE PAR UN PANNEAU. La dérivation existait (étage `stats` scalaire terminal retiré) mais n'était servie que sur les ALERTES — donc atteignable seulement depuis une alerte déjà levée. `/api/rules` la porte désormais À CÔTÉ de la requête telle qu'elle compte ; le SQL brut est rendu INTACT avec ses marqueurs de fenêtre (le lien d'alerte les substitue, ce qui figerait la fenêtre d'un panneau — l'écart est joué dans le test)
include!("index_de_champ_chaud.rs"); // P6.8-d : LES INDEX DE CHAMP CHAUD SE CONSTATENT AU CATALOGUE — l'attente est DÉRIVÉE de `HOT_FIELDS` et de la règle de nommage du produit (aucun nom de champ ni d'index écrit dans le test), confrontée à `sqlite_master` sur une base construite par le VRAI chemin de démarrage (schema.sql + chaîne de migrations + réconciliateur synchrone + tâche de fond). Les DEUX sens du levier `PLUME_EXPRINDEX` sont tenus (armé -> chacun existe ; éteint -> aucun ne subsiste), le régime est LU par la voie du produit et NOMMÉ dans chaque verdict, et la réciproque accuse l'index de la famille sans champ déclaré — dont il est prouvé qu'il SURVIT au kill-switch, ce qui est la raison d'être de l'inclusion inverse
include!("compte_rendu_de_la_passe_d_index.rs"); // P6.8-f : LE COMPTE RENDU DE LA PASSE D'INDEX EST CONSTATÉ AU CATALOGUE, PAS RÉCITÉ DEPUIS LA DÉCLARATION — la passe annonçait `EXPR_INDEX_FIELDS.len()` index « présents » quoi qu'il arrive, après avoir pourtant capturé et écrit chaque échec de création ; et son court-circuit fait que cette ligne ne s'imprime QUE lorsqu'elle travaille, c'est-à-dire exactement quand une création peut échouer. La mutation nomme LA valeur qui change (le compte annoncé), son témoin inverse interdit un verdict qui accuserait toujours, et l'instrument est VALIDÉ à part : un nom déjà porté par un objet d'un autre type fait échouer `CREATE INDEX IF NOT EXISTS` sur le moteur réellement lié — un mode d'échec de terrain, aucun drapeau de test dans le produit
include!("index_de_champ_chaud_orphelin.rs"); // P6.8-e : UN CHAMP RETIRÉ DE LA LISTE CHAUDE NE LAISSE PLUS SON INDEX À VIE — le réconciliateur ne droppant que les noms qu'il DÉRIVE de la liste courante, retirer un champ retirait du même geste la seule chose qui savait nommer son index (disque + une écriture d'arbre par ligne ingérée, à jamais, hors d'atteinte même du kill-switch). Le retrait de fond dérive son périmètre du PRÉFIXE de la famille, seul critère qui survive au retrait d'un champ, sur le modèle de la purge voisine `idx_ev_auto_*`. Mutation dans les deux sens par le VRAI point d'entrée (l'orphelin disparaît ; l'index d'un champ DÉCLARÉ survit), prudence d'un geste inconditionnel (un homonyme qui n'est pas un index n'est pas touché), le piège du levier tranché ET vérifié (le retrait PRÉCÈDE la lecture de `PLUME_EXPRINDEX`, sans quoi une installation ayant éteint la famille garderait ses orphelins), et la confrontation anti-no-op du préfixe à ce que le produit CRÉE — les index étant retrouvés par l'EXPRESSION qu'ils portent, jamais par leur nom
include!("constat_de_presence_des_index.rs"); // P6.8-g : LE CONSTAT DE PRÉSENCE D'UN INDEX COMPARE LA DÉFINITION, PAS L'ÉTIQUETTE — le constat interrogeait le catalogue sur le seul NOM, si bien qu'un objet de type index portant le nom attendu mais posé sur une AUTRE table (ou sur une autre expression) était compté « présent » : le court-circuit de la passe sortait sans rien faire et le vrai index n'était JAMAIS créé, sans une ligne ni une alerte — et la création étant idempotente sur le NOM, elle ne délogeait pas l'occupant, donc l'état était STABLE. La comparaison porte sur ce qui est stable (la table, colonne du catalogue ; le chemin JSON du champ, littéral que SQLite conserve tel quel) et non sur le texte du DDL, qu'une reformulation ferait virer au faux rouge. Deux mutations nomment le compte annoncé (homonyme posé ailleurs, puis homonyme sur la bonne table mais sur une autre expression), une troisième nomme le TRAVAIL de la passe (tous les noms occupés : elle court-circuitait, elle travaille), et le témoin inverse vaut confrontation anti-no-op — si l'attente cessait de correspondre à la DDL, chaque index créé serait déclaré mal posé
include!("quota_de_deversement.rs"); // P10.1-b : LA TAILLE DU DÉVERSEMENT EST BORNÉE, OU L'ABSENCE DE BORNE EST DITE — une fois l'échange de confidentialité pris, RIEN ne bornait la taille écrite en clair hors de la base chiffrée. Le moteur DÉLIE son temporaire aussitôt ouvert, donc lister le répertoire de déversement rend zéro pendant qu'un tri y écrit : la voie « surveiller le répertoire » est RÉFUTÉE ici même, par un fichier délié que la mesure voit et que le listage ne voit pas. Ce qui reste observable est le DESCRIPTEUR que le processus détient, et ce qui impose la borne est le rappel de progression — la seule prise sur une instruction en cours. Mutation dans les deux sens sur un tri qui déverse pour de vrai (quota étroit : refus qui nomme la cause et le levier ; quota large : le MÊME tri rend toutes ses lignes), la note de refus consommée pour qu'une requête suivante ne se voie pas refuser pour une cause qui n'est pas la sienne, et les deux verdicts qui NE bornent RIEN — quota retiré, quota impraticable — distincts l'un de l'autre et dits par la bannière
include!("file_de_riposte_bornee.rs"); // P11.17-e : LA FILE DE RIPOSTE DIT CE QU'ELLE SERT — la route bornait sa lecture à cent lignes et ne rendait QUE ces lignes, si bien que le seul chiffre dont la console disposait était un compte de FENÊTRE que le lecteur prend pour un total, sur la file des gestes de riposte. Le total borné de `/api/query` est repris ici (`PAGINATION_COUNT_CAP`, `total_capped`) : la valeur qui change le dit — le registre passant de 3 à 250 puis 5 000, `served` sature à la fenêtre pendant que `total` suit —, le plafond est annoncé au lieu d'être inventé, le coût du comptage cesse de suivre le volume (contre-exemple porté par le test), et une garde DÉRIVÉE tient la propriété au-delà de ce module : un énoncé qui prend les N dernières lignes d'une table ENTIÈRE (aucun `WHERE`, aucun agrégat, un `ORDER BY`, `LIMIT` ≥ 2 ou posé par gabarit) est une TRONCATURE et non une réponse, donc le chemin qui l'émet — lui-même ou son appelant, un fabricant pur ne rendant aucune réponse — doit porter un total ou un curseur ; trois écarts de la même famille sont nommés par leur TABLE avec leur raison, sous un cliquet qui ne remonte pas
include!("une_liste_servie_dit_son_total.rs"); // P11.17-f : TROIS AUTRES LISTES DISENT CE QU'ELLES SERVENT — trouvées par la garde DÉRIVÉE de `P11.17-e` et non par une relecture, sous un cliquet qui DESCEND ici à zéro. L'inventaire des indicateurs (le plus grave : tronqué en silence, il se lit comme une COUVERTURE) et le registre des engagements reçoivent le total borné partagé ; le classement des entités à risque, dont la borne est DÉLIBÉRÉE (l'ordre `score DESC` répond à la question posée, et la table est reconstruite à blanc à chaque tick), DÉCLARE sa coupe. Ce que la clé et les index de CHAQUE table permettent est vérifié et non supposé : `ioc.last_seen` n'est indexé par rien — la borne borne l'ENVOI, pas la lecture, et le contre-exemple qui balaie vraiment est la fenêtre servie elle-même —, `ioc_upsert` réécrit `last_seen` donc un curseur y désignerait une ligne qui se DÉPLACE, et `engagement.id` étant un texte tiré de /dev/urandom, le curseur sur l'identifiant seul de `P11.17-e` est RÉFUTÉ ici avec son instrument validé dans les deux sens. Sur le classement, un total seul ne suffisait pas : la pastille de seuil est une DISJONCTION que l'ordre par score ignore, donc la réponse porte aussi le compte d'entités au-dessus d'un seuil, par le MÊME prédicat que les lignes et que le moteur d'alerte
include!("controles_de_defense.rs"); // P11.18-i : UNE ALERTE DE CONTRÔLES QU'ON PEUT LIRE, ET UN CATALOGUE VIDE QUI SE DIT — l'alerte n'annonçait qu'un COMPTE alors que les trois réponses attendues étaient DÉJÀ en base (la liste des contrôles dans `alert.detail`, la machine dans `alert.host`, la borne de temps dans la série d'instantanés où une ligne par état survit au heartbeat) ; elle NOMME désormais les manquants, la machine et le dernier état différent, dit le compte comme un MINORANT tant qu'un verdict n'est pas établi, et dit l'écart quand la charge annonce plus qu'elle ne nomme. Un catalogue VIDE cesse de sortir en silence : la propriété est « zéro contrôle évalué », jamais la RAISON du zéro, et une charge sans liste n'autorise aucune affirmation. Garde DÉRIVÉE sur les capteurs livrés — le catalogue générique n'interroge plus un pare-feu que l'autre voie porte déjà avec sa propre alerte, avec les deux contrôles positifs sans lesquels elle rendrait vert en ne voyant rien
include!("magasin_de_secrets.rs"); // P9.8-a : UN MAGASIN DE SECRETS QUI NE PEUT PLUS SERVIR ÉTEINT LA ROTATION DES CLÉS — mesuré en vrai : un coffre scellé plusieurs jours a bloqué VINGT-SEPT secrets externes de tous les espaces d'un cluster (émetteur de certificats, fournisseur d'identité, tunnel d'entrée, pare-feu applicatif), deux certificats ne se sont pas renouvelés pendant un mois, et RIEN ne l'a dit hors d'une commande d'exploitant. Le signal porte sur le MAGASIN et non sur ses consommateurs (UNE alerte, pas vingt-sept), il exige l'unanimité des relevés d'une heure pour lever et UN seul relevé sain pour se résoudre en libérant sa clé, il ne conclut RIEN sans relevé — ni levée ni résolution, un capteur qui se tait ne vaut jamais « l'approvisionnement est reparti » — et une lecture impossible est AVOUÉE au bilan de tick. La mutation nomme la valeur qui bascule le verdict (le nombre de relevés, 1 puis 2), le témoin inverse interdit une sonde qui alerterait toujours, et le coût est compté par SQLite sous mutation du volume x4 avec son CONTRÔLE POSITIF dans le même corps (la cadence de la série, elle, doit se voir)
include!("entrees_scriptees_bornees.rs"); // P4.6-a + P4.6-b : LES DEUX BORNES DE L'ENTRÉE SCRIPTÉE COUPENT EN LE DISANT — la commande déclarée par l'exploitant n'était bornée par RIEN (mesuré : `sh -c 'echo debut; sleep 300'` ne rendait pas la main, le spool restait VIDE, et la ligne déjà lue mourait avec le processus tué), et le plafond par passage jetait le surplus en SILENCE (mesuré : `seq 1 10` sous `MAX=3` → 3 événements, 7 lignes perdues, aucun aveu, code 0). Le capteur est exécuté TEL QU'IL EST LIVRÉ : la coupure de durée rend la main et publie ce qui avait été lu, le plafond rend le NOMBRE de lignes écartées, et les deux aveux empruntent le canal sur lequel la règle livrée alerte (`collect_status=unavailable`), imputés à LA source tronquée. Les deux témoins INVERSES sont exigés — sous le plafond, aucun aveu et les 10 lignes publiées ; `TIMEOUT=0`, le même capteur sur la même commande attend la fin, ce qui prouve que c'est la BORNE qui rend la main. Une borne non entière (`MAX=deux`), qui faisait disparaître l'entrée ENTIÈRE avec un code 0, retombe sur son défaut et le dit
include!("allowlist_du_responder.rs"); // P4.7-a : UN MÊME FICHIER D'ALLOWLIST PORTAIT DEUX POLITIQUES — `/etc/plume/responder.allow` est écrit par les DEUX installateurs (qui ne le créent que s'il est ABSENT) et lu par DEUX composants : noms de SERVICE pour `stop_service` côté démon, ADRESSES à ne jamais bannir côté agent. La direction dangereuse est MESURÉE et non supposée : avec `nginx.service` dans la liste, `collectors/respond.sh` ne trouvait aucune adresse épargnée et POSAIT le ban. Le lecteur du démon REJETTE désormais une liste de l'autre politique au lieu de la lire comme une liste de services vide, par un CLASSIFICATEUR de forme d'adresse — et `P4.7-b` a mesuré que ce classificateur n'est PAS, et ne peut pas être, « le prédicat de la cible d'un ban » : ce sont DEUX questions (ce qu'on sait BANNIR / ce qu'une LIGNE est), leurs réponses diffèrent sur toute la famille IPv6, et un témoin interdit qu'on en refasse une seule ; ce qui est tenu entre les deux lecteurs est la CONTENANCE, décomposée en deux moitiés BALAYÉES et reliées par la borne structurelle publiée dans `collectors/predicat-adresse.corpus` ; une lecture impossible cesse d'être rendue comme une liste vide ; et le chemin se pose (`PLUME_STOP_SERVICE_ALLOW`) pour SÉPARER les deux politiques sur une machine qui porte les deux rôles. Deux témoins inverses tiennent la porte — une liste de services reste lue, et le fichier que l'installateur POSE (lu dans `bootstrap.sh`, jamais recopié ici) vaut « liste vide » et non un refus. Le versant agent est tenu, armé, par `check_enforcer_lists_fail_closed.py`
include!("portillon_avoue.rs"); // P10.7-c : LE PORTILLON AVOUE, UNE FOIS, POUR TOUTES LES ROUTES QUI LE FRANCHISSENT — le défaut « corps vide NU quand le sémaphore interactif est clos » avait été fermé DEUX fois au cas par cas et l'index en annonçait une troisième occurrence : le balayage dérivé en trouve ONZE le 2026-08-28, sur dix-neuf sites d'acquisition. L'aveu quitte les routes pour `handlers/portillon`, seul point qui écrit la cause, et la garde porte sur la FORME de la branche `Err` — population découverte par parcours de `daemon/src/`, jamais énumérée, complète PAR COMPOSITION avec la garde `P7.8-a` qui interdit toute autre écriture de l'acquisition. La jambe exécutée sert le routeur RÉEL portillon CLOS puis OUVERT sur les MÊMES requêtes (la valeur qui change est la présence de la cause, et un correctif « avoue toujours » meurt au second balayage), et elle VÉRIFIE SA PROPRE COUVERTURE : une fonction qui rend un corps de refus et qu'aucune sonde n'atteint fait rougir le test au lieu d'être déclarée couverte sans avoir été vue
include!("panneau_avoue.rs"); // P10.5-i : UN PANNEAU DIT JUSQU'OÙ IL A PU VOIR, ET LE NOMBRE NE BOUGE PAS — une réponse de panneau était calculée sur la seule fenêtre que la rétention (et le vieillissement froid) avait laissée, puis rendue comme une courbe ENTIÈRE ; le cas fondateur, une courbe VIDE annoncée « aucune donnée sur la fenêtre », est une phrase FAUSSE (il y a eu des données, elles sont sous l'horizon). L'aveu est estampé par le SEUL consommateur d'un panneau compilé, sur les SIX points d'exécution mesurés, et il a TROIS états de provenance parce que deux auraient AJOUTÉ un mensonge (« brut / exact ») sur onze panneaux livrés dont le SQL lit un pré-agrégé plafonné en top-N. Témoins : positif sur la famille la plus amputée, trois négatifs dont l'ANTI-FATIGUE (fenêtre « Tout » -> rien à annoncer) et la marge dérivée du cache, mutation sur LA valeur (le levier de rétention, écart exact de (90−7) jours) et sa jumelle sur le DÉFAUT (pool indisponible -> aucun horizon, jamais un plancher fabriqué), couple provenance opaque/routée avec le geste naïf rejoué en mutant, identité BYTE À BYTE de `columns`/`rows` sur les familles semées, deux gardes DÉRIVÉES avec leur plancher de non-dégénérescence (la table du cache, la table de routage + la FORME du corps), et la re-estampe SWR qui ne certifie PAS une fenêtre que les lignes n'ont pas vue
include!("fermeture_shell_spa.rs"); // P4.13-a : SANS MANDATAIRE, L'ÉCRAN DE LOGIN NE POUVAIT JAMAIS S'AFFICHER — le statique est servi par le repli, ENVELOPPÉ par la garde d'authentification, dont la liste d'exemption (quatre chemins : deux icônes, le manifeste, le service-worker) ne portait ni la racine ni le script d'entrée : `GET /` rendait douze octets de texte brut et le module qui PEINT l'écran de login n'était jamais chargé. L'exemption est DÉRIVÉE et non énumérée — fermeture des imports ES statiques depuis `/app.js` (49 des 50 modules ; le 50e, `sw.js`, était déjà exempté), plus ce que le document d'entrée et sa feuille référencent directement — puis RECALCULÉE ici et comparée DANS LES DEUX SENS (atteignable mais absent -> login cassé ; présent mais inatteignable -> surface publique morte). L'instrument est validé sur le faux positif MESURÉ du dépôt (« post-import ( » en prose française, lu comme un import dynamique par un motif naïf) ET sur son inverse (un vrai `import(` doit être VU). La preuve est PAR SERVICE : le routeur RÉEL monté sur le `web/` livré, interrogé en HTTP sans identité — la racine rend le shell, les 61 chemins exemptés sont rendus BYTE À BYTE, et les deux témoins négatifs tiennent (toutes les lectures de la table de routage restent 401 ; aucun fichier de `web/` hors fermeture, ni voisin de nom, ne devient public)
include!("chemin_masque_sans_permis.rs"); // P10.18-a : LA PHRASE QUI CORRIGE UN COMMENTAIRE FAUX NE PORTE PLUS DE CHIFFRE — le doc-comment de `panel_data_masked_live`, posé pour démentir un mécanisme inexistant, adossait sa correction à un COMPTE des acquisitions de permis du module ; ce compte comptait des occurrences de TEXTE (2 appels réels contre 7 occurrences dans le fichier, mesuré le 2026-08-30 ; 11 appels sur 8 fichiers pour `daemon/src` hors tests). La propriété remplace le nombre — aucune acquisition de permis de ce module ne vit dans le corps de cette fonction — et elle est DÉRIVÉE du fichier par un dépouilleur validé dans les deux sens sur des corpus FABRIQUÉS (positif : appels réels distingués des mentions en commentaire de ligne, de bloc, en chaîne multiligne et en littéral de caractère, avec vérification des LIGNES — blanchir un littéral multiligne sans garder ses retours décale de sept ; négatif : prose seule -> zéro ; mutant : un permit pris dans un corps fabriqué DOIT être vu). Anti-no-op sur la tranche retenue, et le compromis est écrit : retirer une acquisition AILLEURS laisse vert, parce que l'exiger contraire serait une rançon
include!("posture_non_lue.rs"); // P10.7-e : ce qui échoue APRÈS le portillon cesse de rendre un corps vide NU — deux témoins sur les deux routes de conformité, chacun exigeant que son chemin NOMINAL reste MUET (un aveu inconditionnel n'est pas un aveu), et le second séparant deux faits que le corps confondait : un journal d'intégrité VIERGE (une absence ÉTABLIE) et un journal NON LU (un aveu)
include!("troncature_sous_budget.rs"); // P10.7-f : un RÉSULTAT PARTIEL cessait d'être servi comme un TOTAL — la garde de budget interrompt le parcours EN COURS D'ITÉRATION et `query_map(..).flatten()` rendait un PRÉFIXE bien formé, sans marque, indiscernable d'une page complète (mesuré : 51 lignes sur 200, aucune erreur). Le parcours DISTINGUE désormais la fin normale de l'interruption ; deux faits mesurés le même jour gouvernent sa forme et sont tenus ici — une erreur du MAPPEUR ne tarit pas l'itérateur (s'arrêter à la 1re erreur aurait tronqué un chemin nominal), et une interruption ne porte que sur l'énoncé EN VOL (donc l'aveu est adossé à l'erreur VUE, jamais au tir de la garde). Témoin négatif dans les deux corps : le chemin nominal doit rester MUET après qu'on a vérifié qu'il a bien tout rendu
include!("ce_qui_n_a_pas_ete_fait_se_dit.rs"); // P10.7-m + P11.22-e : un RÉSULTAT VIDE et un TRAVAIL NON FAIT avaient la même forme. (A) `sla_policy_upsert` rendait `204` = « fait » dans TROIS cas où ce mot était faux — l'écriture de la politique elle-même avalée par un `let _ =` (et ledgerisée quand même), la liste des cases à recalculer illisible (`unwrap_or_default()` -> zéro recalcul, boucle à vide), et la borne de 5000 franchie sans un mot ; le recalcul devient une fonction PURE qui rend un COMPTE et un MANQUE, et la route ne parle que quand « fait » serait faux (témoin négatif : le nominal reste `204` SANS CORPS, et la borne EFFLEURÉE reste muette — ce cas-là seul sépare un aveu mesuré par la ligne excédentaire d'un aveu déduit de `len()==plafond`). (B) RÉFUTATION MESURÉE de l'énoncé fondateur : un maillon de journal écrit avec un hachage précédent VIDE n'est PAS indétectable — `verify_ledger_conn` et `ledger_verify_export` le NOMMENT tous deux, instrument validé dans les deux sens (quatre maillons du vrai chemin restent muets, le cinquième forgé accuse) ; le témoin existe pour que la rupture ne devienne jamais TOLÉRABLE, deux des trois issues offertes à `ledger_append` l'exigeant. (B bis) LA MOITIÉ ÉCRITURE, FERMÉE le 2026-08-31 : `ledger_prev_hash` DISCRIMINE SUR L'ERREUR — `QueryReturnedNoRows` = journal vierge = origine LÉGITIME (première écriture nominale, qui réussit et reste muette), toute AUTRE erreur = on ignore à quoi s'accrocher, donc `ledger_append` REFUSE d'écrire (aveu conditionnel sur stderr, jamais le `detail`) et `audit_source_change` fait REMONTER pour que l'appelant annule ; AUCUNE signature ne change (61 sites `ledger_append` sur 14 fichiers + 114 sites du double-audit sur 34, tous INTACTS) et le vérificateur n'est PAS touché — mesuré par mutation que ses deux ancrages, la comparaison `prev_hash != prev` ET le recalcul sur le maillon courant, mordent CHACUN SEUL, ce qui condamnait les deux autres issues (marquer la rupture / déclarer une chaîne neuve) à créer le chemin par lequel une chaîne rompue devient verte. (C) l'inventaire des `source` lit UNE ligne de plus que sa borne et sert `values.source_capped` — mesuré sur la VRAIE constante (500 sert et se tait, 501 sert 500 et le dit), le corps de la route extrait en fonction PURE pour que l'aveu soit prouvé ATTEINDRE le client et pas seulement être calculé ; ce qu'il ne couvre pas est écrit (un rollup ILLISIBLE rend vide sans s'avouer écourté — le défaut de (A) sur une autre lecture, laissé OUVERT)
